@WhatToEat.API_HostAddress = https://localhost:7263

GET {{WhatToEat.API_HostAddress}}/api/whatToEat

###


GET {{WhatToEat.API_HostAddress}}/api/whatToEat/1018

###


POST {{WhatToEat.API_HostAddress}}/api/whatToEat
Content-Type: application/json

{
  "Text": "Te gustaria una comida caliente"
}

###


DELETE {{WhatToEat.API_HostAddress}}/api/whatToEat/1018

###

PATCH {{WhatToEat.API_HostAddress}}/api/whatToEat/1017
Content-Type: application/json

{
  "Text": "Pregunta actualizada"
}

###