@WhatToEat.API_HostAddress = https://localhost:7263

GET {{WhatToEat.API_HostAddress}}/api/whatToEat

###


GET {{WhatToEat.API_HostAddress}}/api/whatToEat/1015

###


POST {{WhatToEat.API_HostAddress}}/api/whatToEat
Content-Type: application/json

{
  "Text": "Te gustaria una comida caliente"
}

###


DELETE {{WhatToEat.API_HostAddress}}/api/whatToEat/1018

###

PATCH {{WhatToEat.API_HostAddress}}/api/whatToEat/1017
Content-Type: application/json

{
  "Text": "Pregunta actualizada"
}

###




POST {{WhatToEat.API_HostAddress}}/api/whatToEat/1015/Answer
Content-Type: application/json

{
  "Text": "coco with shrimp"
}

###

GET {{WhatToEat.API_HostAddress}}/api/whatToEat/1019/Answer

###

GET {{WhatToEat.API_HostAddress}}/api/whatToEat/1/Answer/1

###

DELETE {{WhatToEat.API_HostAddress}}/api/whatToEat/1019/Answer

###

POST {{WhatToEat.API_HostAddress}}/Register
Content-Type: application/json

{
  "email": "miCorreo@hotmail.com",
  "password": "MiContrasenia1$"
}

###

POST {{WhatToEat.API_HostAddress}}/Login
Content-Type: application/json

{
  "email": "miCorreo@hotmail.com",
  "password": "MiContrasenioa1$"
}