@WhatToEat.API_HostAddress = https://localhost:7263
@token = CfDJ8O867qcmep9LudrhFi2DADrscLqbAYNzt928MFNFY5pJnFGMc43-IidnfIoqvW2BG_F6FmhsZpADJMAUGvyT_kfGpzlIgEkXgi8RG77k5BQbmM6rZiOMIaClV24Rv6ZQjIJWvtRHU_9Mx-5SyephluE7pPF-JhvVYoFIvD9BRS5t9C1EVUlmHVEbMPgRv8sBpzJtQYbbdV69tmV3Q9_xN7e2wMLCfXgqtv6jAye5ZLVSvdF9WEbWYVm4h6g4Qls2KBuwE7FaP4B_f-WSTVPa-tNR-abXEP_kvX2WcSnMEHcr0m_oQ_Trmye25qVzsAEwKwgcDag1fUfGokioCUvpzwiDkS9ppz9xKeNjtqZeLAHQPKiNf9sq4tVMOuFObhOh7yLBZYDfYzhKQezdwFb2S4kcsh8ondMemBHgtPvUUUnNxXmWRionVAAUvL8njTy38jN2SNzU-opu7zourmix1m0cyBCyIagTJ-NkuUcAKKSlfXv_EEaT6q-usAfS_D75TfWD-31GXZ5DhpgQcLvqnLoNLFaowdPkH1eQrF9yBIDhJ4M6YcPHIqCJkgPu97FE2Fl-i5jquMSyfS6_hDfts_7qZa7zweilw0AJa4j3UFfCkkux3ldIPDuJ__XzsU_0SWLYdFi33dryv2royusBFRFJOhB_r9zCK2JTbpwrEUDkO5x7YdqgmntO68angH-f3dp4CPersEn_-w2Y5qTAWn0

GET {{WhatToEat.API_HostAddress}}/api/whatToEat

###


GET {{WhatToEat.API_HostAddress}}/api/whatToEat/1015
Authorization: Bearer {{token}}
###


POST {{WhatToEat.API_HostAddress}}/api/whatToEat
Content-Type: application/json

{
  "Text": "Te gustaria una comida caliente"
}

###


DELETE {{WhatToEat.API_HostAddress}}/api/whatToEat/1018

###

PATCH {{WhatToEat.API_HostAddress}}/api/whatToEat/1017
Content-Type: application/json

{
  "Text": "Pregunta actualizada"
}

###




POST {{WhatToEat.API_HostAddress}}/api/whatToEat/1015/Answer
Content-Type: application/json

{
  "Text": "coco with shrimp"
}

###

GET {{WhatToEat.API_HostAddress}}/api/whatToEat/1019/Answer

###

GET {{WhatToEat.API_HostAddress}}/api/whatToEat/1/Answer/1

###

DELETE {{WhatToEat.API_HostAddress}}/api/whatToEat/1019/Answer

###

POST {{WhatToEat.API_HostAddress}}/api/identity/Register
Content-Type: application/json

{
  "email": "miCorreo@hotmail.com",
  "password": "MiContrasenia1$"
}

###

POST {{WhatToEat.API_HostAddress}}/api/identity/Login
Content-Type: application/json

{
  "email": "miCorreo@hotmail.com",
  "password": "MiContrasenia1$"
}
###

PATCH {{WhatToEat.API_HostAddress}}/api/indetity/user
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "dateOfBirth": "2024-10-11",
  "nationality": "Other"
}

###